//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAspnet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPRISEntities12 : DbContext
    {
        public OPRISEntities12()
            : base("name=OPRISEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Ads> Table_Ads { get; set; }
        public virtual DbSet<Table_Company> Table_Company { get; set; }
        public virtual DbSet<Table_Rubrics> Table_Rubrics { get; set; }
        public virtual DbSet<Table_Users> Table_Users { get; set; }
    }
}
