//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Users
    {
        public int id_User { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
        public string userRole { get; set; }
        public Nullable<int> id_Company { get; set; }
    
        public virtual Table_Company Table_Company { get; set; }
    }
}
